/*
Descripción: Ventana Configuración del Proyecto
Fecha: 26/Junio/2022
Nombre: David Enrique Garcia Olvera
 */
package vista;

/**
 *
 * @author David García
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfiguracion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblGeneral = new javax.swing.JLabel();
        btnOpciones = new javax.swing.JButton();
        btnCajeros = new javax.swing.JButton();
        lblGeneral1 = new javax.swing.JLabel();
        btnImpuestos = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnMoneda = new javax.swing.JButton();
        btnConfHome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVentas = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenu();
        menuProveedores = new javax.swing.JMenu();
        menuInventario = new javax.swing.JMenu();
        menuConfiguracion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración");

        lblConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfiguracion.setText("Configuración");

        lblGeneral.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGeneral.setText("General");

        btnOpciones.setText("Opciones");
        btnOpciones.setToolTipText("");

        btnCajeros.setText("Cajeros");
        btnCajeros.setToolTipText("");

        lblGeneral1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGeneral1.setText("Personalización");

        btnImpuestos.setText("Impuestos");
        btnImpuestos.setToolTipText("");

        btnTicket.setText("Ticket");
        btnTicket.setToolTipText("");

        btnMoneda.setText("Símbolo de Moneda");
        btnMoneda.setToolTipText("");

        btnConfHome.setText("Mostrar todas las opciones");
        btnConfHome.setToolTipText("");

        menuVentas.setText("Ventas");
        jMenuBar1.add(menuVentas);

        menuClientes.setText("Clientes");
        jMenuBar1.add(menuClientes);

        menuProductos.setText("Productos");
        jMenuBar1.add(menuProductos);

        menuProveedores.setText("Proveedores");
        jMenuBar1.add(menuProveedores);

        menuInventario.setText("Inventario");
        jMenuBar1.add(menuInventario);

        menuConfiguracion.setText("Configuración");
        jMenuBar1.add(menuConfiguracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfiguracion)
                    .addComponent(lblGeneral)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCajeros))
                    .addComponent(lblGeneral1)
                    .addComponent(btnConfHome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImpuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoneda)))
                .addContainerGap(901, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfHome)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpciones)
                    .addComponent(btnCajeros))
                .addGap(18, 18, 18)
                .addComponent(lblGeneral1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTicket)
                    .addComponent(btnImpuestos)
                    .addComponent(btnMoneda))
                .addGap(0, 435, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCajeros;
    public javax.swing.JButton btnConfHome;
    public javax.swing.JButton btnImpuestos;
    public javax.swing.JButton btnMoneda;
    public javax.swing.JButton btnOpciones;
    public javax.swing.JButton btnTicket;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblGeneral;
    private javax.swing.JLabel lblGeneral1;
    public javax.swing.JMenu menuClientes;
    public javax.swing.JMenu menuConfiguracion;
    public javax.swing.JMenu menuInventario;
    public javax.swing.JMenu menuProductos;
    public javax.swing.JMenu menuProveedores;
    public javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
