/*
 * Descripccion: VENTANA PROVEEDORES
 * Alumno: JOSÉ LUIS ROCHA LÓPEZ
 * Fecha: 26/06/2022
 */
package vista;

/**
 *
 * @author Ching
 */
public class proveedores extends javax.swing.JFrame {

    /**
     * Creates new form proveedores
     */
    public proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedores = new javax.swing.JTable();
        LBproveedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BTTNuevoProveedor = new javax.swing.JButton();
        BTTModificarProveedor = new javax.swing.JButton();
        BTTEliminarProveedor = new javax.swing.JButton();
        LBProveedores = new javax.swing.JLabel();
        LBNombreProveedor = new javax.swing.JLabel();
        TXTNombreProveedor = new javax.swing.JTextField();
        BTTBuscar = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnMenuVentas = new javax.swing.JMenu();
        BtnMenuClientes = new javax.swing.JMenu();
        BtnMenuProductos = new javax.swing.JMenu();
        BtnMenuProveedores = new javax.swing.JMenu();
        BtnMenuInventario = new javax.swing.JMenu();
        BtnMenuConfiguracion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProveedores", "Nombre Proveedor", "RFC", "Telefonos", "Correo", "Calle Y Numero", "Colonia", "Municipio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProveedores);
        if (TablaProveedores.getColumnModel().getColumnCount() > 0) {
            TablaProveedores.getColumnModel().getColumn(0).setResizable(false);
            TablaProveedores.getColumnModel().getColumn(1).setResizable(false);
            TablaProveedores.getColumnModel().getColumn(2).setResizable(false);
            TablaProveedores.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1020, 430));

        LBproveedor.setText("PROVEEDORES");
        getContentPane().add(LBproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1020, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 10));

        BTTNuevoProveedor.setText("Nuevo");
        getContentPane().add(BTTNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        BTTModificarProveedor.setText("Modificar");
        BTTModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTModificarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(BTTModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        BTTEliminarProveedor.setText("Eliminar");
        getContentPane().add(BTTEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        LBProveedores.setBackground(new java.awt.Color(255, 153, 51));
        LBProveedores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBProveedores.setForeground(new java.awt.Color(255, 153, 51));
        LBProveedores.setText("PROVEEDORES");
        getContentPane().add(LBProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        LBNombreProveedor.setText("Nombre del Proveedor");
        getContentPane().add(LBNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        TXTNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(TXTNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, -1));

        BTTBuscar.setText("Buscar");
        getContentPane().add(BTTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 80, -1));

        BtnMenuVentas.setText("Ventas");
        jMenuBar1.add(BtnMenuVentas);

        BtnMenuClientes.setText("Clientes");
        jMenuBar1.add(BtnMenuClientes);

        BtnMenuProductos.setText("Productos");
        jMenuBar1.add(BtnMenuProductos);

        BtnMenuProveedores.setText("Proveedores");
        jMenuBar1.add(BtnMenuProveedores);

        BtnMenuInventario.setText("Inventario");
        jMenuBar1.add(BtnMenuInventario);

        BtnMenuConfiguracion.setText("Configuracion");
        jMenuBar1.add(BtnMenuConfiguracion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTTModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTModificarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTTModificarProveedorActionPerformed

    private void TXTNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton BTTBuscar;
    public javax.swing.JButton BTTEliminarProveedor;
    public javax.swing.JButton BTTModificarProveedor;
    public javax.swing.JButton BTTNuevoProveedor;
    public javax.swing.JMenu BtnMenuClientes;
    public javax.swing.JMenu BtnMenuConfiguracion;
    public javax.swing.JMenu BtnMenuInventario;
    public javax.swing.JMenu BtnMenuProductos;
    public javax.swing.JMenu BtnMenuProveedores;
    public javax.swing.JMenu BtnMenuVentas;
    private javax.swing.JLabel LBNombreProveedor;
    private javax.swing.JLabel LBProveedores;
    private javax.swing.JLabel LBproveedor;
    private javax.swing.JTextField TXTNombreProveedor;
    public javax.swing.JTable TablaProveedores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
